### ISSUE TITLE
Mini-Cart button shows items contains after submit

### ISSUE THREAD

**Issue by X-Tender** [extcode/cart#323] opened 2021-02-11 15:45 UTC
## Bug Report

**Current Behavior**
When the Order get submitted and the success state is shown, the mini cart button still show that he have items in it. after clicking on it or change page the mini-cart is shown as empty.

**Expected behavior/output**
After the order was submitted the minicart should be shown empty

**Environment**
- TYPO3 version(s): 9 latest
- cart version: 6.9.2
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: linux

**Comment by medarob** [comment] 2021-10-19 21:07
I used this code, which I found in the #cart slack channel, for the mini cart
```
lib.cart_header = COA
lib.cart_header {
  10 = USER
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Cart
    pluginName = MiniCart
    vendorName = Extcode
    controller = Cart\CartPreview
    switchableControllerActions {
      Cart\CartPreview {
        1 = show
      }
    }
  }
}
```
and added it as a test to our header fluid code with
```
<f:cObject typoscriptObjectPath="lib.cart_header"/>
```

After submitting the order, the number of items will be kept.

If I change the `lib.cart_header` to `COA_INT` and `10` to `USER_INT` the mini cart shows 0 after submitting the order.

Not sure if there is any other way to add a mini cart to the header and if so, if that will help?

(Would be great to have this as an example in the documentation, maybe a page: "How to add a mini cart to the header")

**Comment by rintisch** [comment] 2024-03-23 14:19
I tried in TYPO3 v12 the new content object [`EXTBASEPLUGIN`](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Extbaseplugin/Index.html)

```typoscript
lib.miniCart = EXTBASEPLUGIN
lib.miniCart {
  extensionName = Cart
  pluginName = MiniCart
}
```

The problem is the same, after submitting the order the cart still shows the old status before submitting. 

So I tried the (updated) solution of @medarob 

```typoscript
lib.miniCart = COA_INT
lib.miniCart {
  10 = USER_INT
  10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = Cart
    pluginName = MiniCart
    vendorName = Extcode
  }
}
```

Which works well for me. 

@extcode I suggest adding this as snippet to the documentation and will create a PR when solving #454.

**Comment by rintisch** [comment] 2024-05-25 10:00
I will close this issue as a proper implementation is now documented after mergin #454

**Closed by rintisch** 2024-05-25 10:00 UTC
