### ISSUE TITLE
Invoice number is not displayed in the order summary

### ISSUE THREAD

**Issue by msdevl** [extcode/cart#16] opened 2016-09-22 05:54 UTC
I've created a new, according to the following pattern: XXXXXXXXXX0001, , but it is not displayed in the order summary.

**Comment by rintisch** [comment] 2024-03-20 22:02
@msdevl 
This is quite a late response but: I guess the problem is solved after all those years!?

**Comment by rintisch** [comment] 2024-04-06 09:41
I will close this ticket due to missing feedback. You're off course still welcome to respond!

**Closed by rintisch** 2024-04-06 09:41 UTC
Labels: needs feedback
