### ISSUE TITLE
Reference Error in 9.x

### ISSUE THREAD

**Issue by paul-keller** [extcode/cart#422] opened 2023-08-10 09:36 UTC
We tried the 9.x dev branch in our installation. But get this error:
The definition "extcode.cart.provider.orders_per_day" has a reference to an abstract definition "TYPO3\CMS\Core\Localization\LanguageService". Abstract definitions cannot be the target of references.

**Comment by BokuNoMaxi** [comment] 2023-08-14 05:49
We get that error too. The cause is in the registration of the dashboard widgets. 

vendor/extcode/cart/Configuration/Backend/Provider/OrdersPerDayProvider.php
vendor/extcode/cart/Configuration/Backend/Provider/TurnoverPerDayProvider.php

This line is the cause: 
        ->arg('$languageService', new Reference(LanguageService::class))
The language service will now be loaded via dependeny injection, simple removing this line would work, but then I get an error on a missing default view...

As a temporary fix to use this version for our typo3 12 update, we forked and deactivated those widgets in 
vendor/extcode/cart/Configuration/Services.php

**Comment by rintisch** [comment] 2023-11-23 10:57
@extcode As I understand it this is also already solved with https://github.com/extcode/cart/pull/427.

**Comment by rintisch** [comment] 2024-03-20 19:35
@extcode 
I guess this can be closed as you cherry-picked the solving commits.

**Closed** 2024-03-20 21:24 UTC
