### ISSUE TITLE
Backend: no display of addresses in the orders

### ISSUE THREAD

**Issue by format-gmbh** [extcode/cart#393] opened 2022-06-14 13:50 UTC
I can't see the customer's address from the "List" module or from the "Orders" module.

**Environment**
- TYPO3 : 11.5.10
- cart version: 8.2.0 and 8.4.0
- Composer Mode: yes

**Possible Solution**
Nach dem ich folgende SQL-Anweisung ausgeführt habe, sind die Adressen zu sehen.
```
UPDATE `tx_cart_domain_model_order_address` SET `record_type` = '\\Extcode\\Cart\\Domain\\Model\\Order\\BillingAddress';
```

**Comment by rintisch** [comment] 2024-03-20 20:33
@format-gmbh 
Did the problem occur afterwards again? I cannot reproduce it.

**Comment by format-gmbh** [comment] 2024-03-21 05:48
Yes, this still occurs. It probably has something to do with overwriting your classes. Could that be?
```
    \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
        ->registerImplementation(
            \Extcode\Cart\Domain\Model\Order\BillingAddress::class,
            \Eyeworkers\EwiCartproducts\Domain\Model\Order\BillingAddress::class
        );
    \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
        ->registerImplementation(
            \Extcode\Cart\Domain\Model\Order\ShippingAddress::class,
            \Eyeworkers\EwiCartproducts\Domain\Model\Order\ShippingAddress::class
        );
```

**Comment by rintisch** [comment] 2024-03-21 06:10
@format-gmbh 
Without any implementation details it's hard to say. Could you test it by removing your overwriting and see whether the error vanishes?

**Comment by format-gmbh** [comment] 2024-04-06 06:30
I apologize for taking so long to reply. I have now run tests without the override and the error does not occur.
In the end, I only overwrote the two models because I wanted to overwrite `public function getSalutationTitleFullName()`. I want to remove `$this->salutation` from the array. But maybe this could be solved differently.

**Comment by rintisch** [comment] 2024-04-06 09:38
Thanks for your feedback!

Maybe I miss some of your requirements but I would overwritten the partial `Resources/Private/Partials/Mail/Header.html` instead.

I will close this issue as the original problem is solved.

**Closed by rintisch** 2024-04-06 09:38 UTC
Labels: needs feedback
