### ISSUE TITLE
Shipping Collapse On Error in Order Form

### ISSUE THREAD

**Issue by extcode** [extcode/cart#404] opened 2022-11-01 20:37 UTC
If a customer enters a different shipping address and forget to check one of the accepance checkboxes, the entered shipping address disapears.

**Comment by rintisch** [comment] 2024-03-20 19:27
@extcode This does not happen on my setup on the current main branch.

**Comment by rintisch** [comment] 2024-05-30 13:25
I close this issue as we cannot reproduce the error (any longer).

**Closed by rintisch** 2024-05-30 13:25 UTC
Labels: bug, 7.x, 8.x, 9.x
