### ISSUE TITLE
wrong backlink to list view

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#9] opened 2016-09-08 20:39 UTC
Hi,
I have a list view (list and show products) and a detail view (product - show view).

The backlink from detail view to list view in the file 'show.html' is a link to detail view and not to list view                                               

`<f:link.action class="btn btn-default" action="list">zurück zur Liste</f:link.action>`

Regards
Hobokens

**Comment by extcode** [comment] 2016-09-08 22:00
This is a known bug. This error is caused by the plugin. The (product - show view) is not allowed to list the products. The view doesn't know, which page with a list view calls this page. A quick fix is to use the javascript history.back() function. I think about tracking the clicks and pages and provide this information by the controller. But that takes a while.

**Comment by Hobokens** [comment] 2016-09-09 08:49
I solved the problem with the javascript history.back() function by myself. But I wasn't sure whether the bug is known.

**Comment by extcode** [comment] 2016-09-09 08:55
You can't know this. I will replace the link in the next bugfix version with the history.back() and add a new task on my feature list for thinking about another solution.

**Comment by extcode** [comment] 2016-09-28 10:52
Should be fixed with version 1.2.4.

**Closed by extcode** 2016-09-28 10:52 UTC
